import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";

import CardGrid from "../components/CardGrid";
import { useFetchPageHook } from "../hooks/index";

const Home: NextPage = () => {
  const [pageCount, setPageCount] = useState(0);

  const { data, isLoading } = useFetchPageHook(pageCount);

  const nextPage = () => {
    const { next } = data;
    if (!next) {
      return null;
    }
    setPageCount((current) => current + 1);
  };

  const previousPage = () => {
    const { previous } = data;
    if (!previous) {
      return null;
    }
    setPageCount((current) => current - 1);
  };

  return (
    <div className="bg-gray-100">
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto p-4">
        <div className="flex flex-row justify-center space-x-4">
          <button onClick={previousPage} className="btn">
            Previous{" "}
          </button>
          <button onClick={nextPage} className="btn">
            Next
          </button>
        </div>
        {!isLoading && <CardGrid pokemonData={data.results} />}
      </div>
    </div>
  );
};

export default Home;
