import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";

import CardGrid from "../components/CardGrid";
import { useFetchPageHook } from "../hooks/index";

const Home: NextPage = () => {
  const [pageCount, setPageCount] = useState(0);

  const { data, isLoading } = useFetchPageHook(pageCount);

  const nextPage = () => {
    const { next } = data;
    if (!next) {
      return null;
    }
    setPageCount((current) => current + 1);
  };

  const previousPage = () => {
    const { previous } = data;
    if (!previous) {
      return null;
    }
    setPageCount((current) => current - 1);
  };

  return (
    <div className="container">
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="button-container">
        <button onClick={previousPage} className="button">
          Previous{" "}
        </button>
        <button onClick={nextPage} className="button">
          Next
        </button>
      </div>
      {!isLoading && <CardGrid pokemonData={data.results} />}
    </div>
  );
};

export default Home;
